### ISSUE TITLE
Specific cell type expression matrix

### ISSUE THREAD

**Issue by antgomo** [kkang7/CDSeq_R_Package#1]
Hi,

i am wondering if it is possible to get expression matrix for each cell type, i mean in the example you have 6 cell types and hence you can get 6 cell type matrix RNA data ( gene by sample)

I am looking at Cell2RNA function but i guess is not what i want

Many thanks in advance

**Comment by antgomo** [comment]
Something like that using your code in Cell2RNA

imagine you want for cell type 1, the rnaseq RPKM normalized given by results$estGEP, so

tmp<-t(apply(as.data.frame(t(t(result$estGEP[,1]))),1, function(x) return(x*result$estProp[1,])))

getting RPKM matrix for cell type 1, 500 genes and 40 samples

**Comment by kkang7** [comment]
> Hi,
> 
> i am wondering if it is possible to get expression matrix for each cell type, i mean in the example you have 6 cell types and hence you can get 6 cell type matrix RNA data ( gene by sample)
> 
> I am looking at Cell2RNA function but i guess is not what i want
> 
> Many thanks in advance

Hi, thanks for your interest in the package. For expression matrix for each cell type, it is returned automatically in the output. If you run the example, result <- CDSeq(...), then result$estGEP should be the estimated gene expression for each cell type. 

Let me know if you have any questions.

**Comment by antgomo** [comment]
Thanks,

maybe i didn't express myself properly:

What i want is a cell specifc expression matrix for each cell type, each one genes in rows and samples in columns.

i.e, following your vignette example with a bulk of 500 genes in 40 samples original matrix, for 6 cell types deconvoluted, 6 matrix of 500 gens by 40 samples

**Comment by kkang7** [comment]
> Something like that using your code in Cell2RNA
> 
> imagine you want for cell type 1, the rnaseq RPKM normalized given by results$estGEP, so
> 
> tmp<-t(apply(as.data.frame(t(t(result$estGEP[,1]))),1, function(x) return(x*result$estProp[1,])))
> 
> getting RPKM matrix for cell type 1, 500 genes and 40 samples

Cell2RNA is a function to convert cell proportion to RNA proportion given that the relative differences  of RNA production in different cell types are known. For example, if cell type 1 generally produce 2 times the RNA compare to cell type 2, then we can do the conversion between cell proportion and RNA proportion. RPKM can be returned only the read counts of cell lines are provided, if such info is not available, then CDSeq won't return RPKM normalized expression, but return gene rate which should be proportional to RPKM values.

**Comment by antgomo** [comment]
Ok, that's i was asking, cell proportions but instead for all samples in all cell types, split the matrix for each cell type creating one matrix of gene *samples using your approach

**Comment by kkang7** [comment]
> Thanks,
> 
> maybe i didn't express myself properly:
> 
> What i want is a cell specifc expression matrix for each cell type, each one genes in rows and samples in columns.
> 
> i.e, following your vignette example with a bulk of 500 genes in 40 samples original matrix, for 6 cell types deconvoluted, 6 matrix of 500 gens by 40 samples

So you need cell-type-specific gene expression of the 6 cell types in each of the 40 samples? i.e. 40 gene expression profile for cell type 1, etc? 

Currently, CDSeq only returns cell-type-specific gene expression once for each cell type. Current model basically assumes each cell type's GEP is the "same" (follow same distribution) across all mixture samples up to multinomial random errors. 

For the given example, CDSeq takes the bulk RNAseq data, say, A, which is a gene by sample matrix, and CDSeq will return two matrices, B, the cell-type-specific gene expression estimation, which is a matrix of size gene by number of cell types, and C, which is a matrix of size number of cell types by sample. Specifically, in the given example, input is A_{500 x 40}, output are B_{500 x 6} and C_{6 x 40}. 

Not sure I answered your questions. but let me know if I wasn't clear or not understanding your questions correctly.

**Comment by antgomo** [comment]
> So you need cell-type-specific gene expression of the 6 cell types in each of the 40 samples? i.e. 40 gene expression profile for cell type 1, etc?
> 

Exactly
> Currently, CDSeq only returns cell-type-specific gene expression once for each cell type. Current model basically assumes each cell type's GEP is the "same" (follow same distribution) across all mixture samples up to multinomial random errors.
> 

So the point is, reading your answer, is not possible to get this marix using the approach commented before, isn't it?

**Comment by kkang7** [comment]
> > So you need cell-type-specific gene expression of the 6 cell types in each of the 40 samples? i.e. 40 gene expression profile for cell type 1, etc?
> 
> Exactly
> 
> > Currently, CDSeq only returns cell-type-specific gene expression once for each cell type. Current model basically assumes each cell type's GEP is the "same" (follow same distribution) across all mixture samples up to multinomial random errors.
> 
> So the point is, reading your answer, is not possible to get this marix using the approach commented before, isn't it?

No, it is not possible for now and I am not aware of any method that is able to do it. Do you mind me asking why you would need such detailed GEP info, i.e. all GEPs of the same cell type in all mixture samples? Or say, suppose you have such info, in the next step of your analysis, what would you do with those GEPs of a same cell type in different mixture sample?  I'm just curious :)

**Comment by antgomo** [comment]
> > > So you need cell-type-specific gene expression of the 6 cell types in each of the 40 samples? i.e. 40 gene expression profile for cell type 1, etc?
> > 
> > 
> > Exactly
> > > Currently, CDSeq only returns cell-type-specific gene expression once for each cell type. Current model basically assumes each cell type's GEP is the "same" (follow same distribution) across all mixture samples up to multinomial random errors.
> > 
> > 
> > So the point is, reading your answer, is not possible to get this marix using the approach commented before, isn't it?
> 
> No, it is not possible for now and I am not aware of any method that is able to do it. Do you mind me asking why you would need such detailed GEP info, i.e. all GEPs of the same cell type in all mixture samples? Or say, suppose you have such info, in the next step of your analysis, what would you do with those GEPs of a same cell type in different mixture sample? I'm just curious :)

Well, the idea is next

With GEP and cell proportions, i can use csfit in csSAM to get differential expressed genes for all the cell types.

My aim with GEP for especific cell type with all genes and samples is to plot a heatmap with differentially expressed genes for this cell type. That’s all. So i was wondering if using your Cell2RNA code with the approach i mentioned above, i could generate a matrix of cell type specific expression for visualization purposes

**Comment by kkang7** [comment]
> > > > So you need cell-type-specific gene expression of the 6 cell types in each of the 40 samples? i.e. 40 gene expression profile for cell type 1, etc?
> > > 
> > > 
> > > Exactly
> > > > Currently, CDSeq only returns cell-type-specific gene expression once for each cell type. Current model basically assumes each cell type's GEP is the "same" (follow same distribution) across all mixture samples up to multinomial random errors.
> > > 
> > > 
> > > So the point is, reading your answer, is not possible to get this marix using the approach commented before, isn't it?
> > 
> > 
> > No, it is not possible for now and I am not aware of any method that is able to do it. Do you mind me asking why you would need such detailed GEP info, i.e. all GEPs of the same cell type in all mixture samples? Or say, suppose you have such info, in the next step of your analysis, what would you do with those GEPs of a same cell type in different mixture sample? I'm just curious :)
> 
> Well, the idea is next
> 
> With GEP and cell proportions, i can use csfit in csSAM to get differential expressed genes for all the cell types.
> 
> My aim with GEP for especific cell type with all genes and samples is to plot a heatmap with differentially expressed genes for this cell type. That’s all. So i was wondering if using your Cell2RNA code with the approach i mentioned above, i could generate a matrix of cell type specific expression for visualization purposes

I see. Currently our method cannot do that. But in fact, I'm working on exactly what you are looking for right now. but it may take me some time to finish. Maybe come back to my GitHub page in a month or two if you still need such method, I may have some beta version of the code.

**Comment by antgomo** [comment]
Thanks Kai!

We’ll be in touch

Kind Regards

Toni

**Comment by kkang7** [comment]
> Thanks Kai!
> 
> We’ll be in touch
> 
> Kind Regards
> 
> Toni

You are welcome Toni. Keep in touch : )
