### ISSUE TITLE
CDSeq not available for R 4.2?

### ISSUE THREAD

**Issue by arielah** [kkang7/CDSeq_R_Package#15]
Hi, I am trying to download CDSeq, but get the following error.

`install.packages("CDSeq")
Installing package into ‘/home/ariel/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘CDSeq’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages`

Is CDSeq not compatible with R 4.2, or is there something I'm doing wrong? I'm run Linux, so the known issue with Macs doesn't apply.

**Comment by kkang7** [comment]
Sorry I haven't been updating the code for a while. I think CRAN archived the package. Is it working if install from GitHub directly?

**Comment by arielah** [comment]
Installing from GitHub worked! Thank you for the quick response :)
