### ISSUE TITLE
No reference Gene expression profiles

### ISSUE THREAD

**Issue by antgomo** [kkang7/CDSeq_R_Package#2]
HI,

i am try to estimate GEP using CDseq, the point is that i don't have reference_gep but i have a "bona fide" matrix of 6 cell type proportions for all my samples, my question is, can i use it in your program to get the GEP specific for this cell types or not?

**Comment by kkang7** [comment]
> HI,
> 
> i am try to estimate GEP using CDseq, the point is that i don't have reference_gep but i have a "bona fide" matrix of 6 cell type proportions for all my samples, my question is, can i use it in your program to get the GEP specific for this cell types or not?

you don't need a reference_gep for running CDSeq. If you have the cell type proportion information for all your samples, you may have two options: using CDSeq, either set the number of cell types to be six or let it estimate the number of cell types. Then compare the CDSeq-estimated cell type proportions to your cell type proportions, if they highly correlated, they maybe an indication that CDSeq found this cell type. option two is to just use regression and plug in the cell type proportion. I believe csSAM may be able to do this when cell type proportion is available.
