### ISSUE TITLE
question about scRNA-seq data and thetheory of CDSeq

### ISSUE THREAD

**Issue by caiquanyou** [kkang7/CDSeq_R_Package#3]
hello ，I read your paper and have some problems :
1.I have scRNA-seq data and how clould i use it to match the algorithm result?
2.I can not understand the real difference from LDA to CDseq? what is CDSeq's gene length means?

**Comment by caiquanyou** [comment]
thanks for answering my question,I try to understand now,could you please tell the pipeline or the psuedocode because I'm not good at matlab?

**Comment by kkang7** [comment]
You're welcome. I think you are in the R package repository instead of the
MATLAB one. If you are familiar with R, you can install the package by
running install_github("kkang7/CDSeq_R_Package").
And ?CDSeq will show minimal info and a quick example. Let me know if you
have any other questions.

**Comment by caiquanyou** [comment]
Hello,kkang
one more queetion about CDSeq:why you choose LDA ? or why do you think Dirichlet distribution is suitable for RNA-seq data?

**Comment by kkang7** [comment]
Good question. We actually addressed a bit about why LDA is our choice.
Essentially, its components consist of Dirichlet-Multinomial which is a
widely used model for count data. RNAseq data is a type of count data
before normalization, even though it's very noisy if you think about the
experimental sequencing procedure but Dirichlet-multinomial is a good
starting point in my opinion.

Best,
Kai

**Comment by caiquanyou** [comment]
Hello，
I got  an error when installing CDSeq into another PC,like below:
installing to /home/dean/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-CDSeq/00new/CDSeq/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'Rcpp' 1.0.1 is being loaded, but >= 1.0.3 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'CDSeq'
* removing '/home/dean/R/x86_64-pc-linux-gnu-library/3.6/CDSeq'
Error: Failed to install 'CDSeq' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpRikdda/file4e372218087/CDSeq_1.0.7.tar.gz' had non-zero exit status
How could I fix this problem?
Best regards
CQY

**Comment by kkang7** [comment]
It seems you need to install a later version of Rcpp on the machine. Could
you try that and see if you still have the error?

Best,
Kai

**Comment by caiquanyou** [comment]
fix it now!
but get this 👍* DONE (CDSeq)
> library(CDSeq)
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users\gerra\Anaconda3\envs\cvxpy/python.exe": system could not find the specified file.
does it matter?

**Comment by caiquanyou** [comment]
and run command below error:
Error in CDSeq(bulk_data = x, beta = 0.5, alpha = 5, cell_type_number = 6,  : 
  length(gene_length) should be equal to nrow(bulk_data)

how to set gene_length??

**Comment by kkang7** [comment]
The warning msg seems saying you need to get the python installed
correctly. maybe try reinstalling python.
gene length can be found from the genome reference such as GENCODE that
RNAseq data used for mapping the reads, but you could leave it as null if
you just need to test the installation.
