### ISSUE TITLE
Including known cell type proportions in CDSeq initial deconvolution

### ISSUE THREAD

**Issue by emmawwinchester** [kkang7/CDSeq_R_Package#6]
Hi there! I am using your package and have run into an issue. 
We know that there are about 7 different cell types in our bulk samples (based on scRNAseq profiling), with one cell type taking up 70-80% of the sample. 
When we apply your deconvolution method, we are only able to pick up that one cell type, even when we increase the number of cell types to many greater than 7 (say to 10-15). 
Is there a way to input known cell type proportions in the initial CDSeq() step?
Thank you!

**Comment by kkang7** [comment]
Hi, currently, there is no explicit way of providing cell type proportion
ranges in the bulk. I would recommend increasing the number of cell types
even larger (for example, set cell type number to be 5:30) and see what the
estimated number of cell types is and if other cell types could be
detected. Make sure the dilution factor is set to be 1. CDSeq may find a
couple of cell types with the same identity if it constitutes a large
proportion in bulk samples, then those cell types can be merged into one
major cell type in the cell type annotation procedure. Another thing you
could try is to decrease hyperparameter alpha to be less than 1 (say 0.1 or
something). alpha less than 1 is saying that the proportions of cell types
are likely to be dominated by a couple of cell types. You can play with
these options and see if the minority cell types could be found.
