### ISSUE TITLE
Input for CDSeq?

### ISSUE THREAD

**Issue by merlevede** [kkang7/CDSeq_R_Package#7]
Dear all,

I am completely new to CDSeq but am very interesting to try it. From what I read so far, I have the feeling that the input should be raw counts and not normalized read counts. Is it correct?
My worry is that a lot of publicly available datasets, as the ones we can get from cbioportal, are provided as normalized counts and there is no way to get raw counts to my knowledge. So, is there no way we can apply CDSeq on such datasets?

Thank you in advance,
Jane

**Comment by kkang7** [comment]
@merlevede Hi Jane sorry for the late response. Yes, the input should be raw counts. normalized data is not ideal. But you could try, at least the normalized data should not be log transformed. We tried some microarray data which works okay in our testing.

**Comment by merlevede** [comment]
Ok, thank you for your answer.
I will try on raw counts, but I have only few datasets that are not normalized already. I work mainly with public data, so I may try on normalized data, not log transformed as you recommended.
